# Generated by Django 5.2 on 2025-07-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reservation_table_alter_menuitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
